"""initial schema

Revision ID: 949daf9b6ae7
Revises: 
Create Date: 2026-08-22 06:24:32.778347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '949daf9b6ae7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('module_path', sa.String(), nullable=False),
    sa.Column('last_active_tick', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('agent_name')
    )
    op.create_table('businesses',
    sa.Column('business_id', sa.String(), nullable=False),
    sa.Column('industry', sa.String(), nullable=False),
    sa.Column('building_id', sa.String(), nullable=False),
    sa.Column('employee_ids', sa.JSON(), nullable=False),
    sa.Column('cash', sa.Float(), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=False),
    sa.Column('expenses', sa.Float(), nullable=False),
    sa.Column('profit', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('business_id')
    )
    op.create_table('citizens',
    sa.Column('citizen_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.Column('household_id', sa.String(), nullable=True),
    sa.Column('occupation', sa.String(), nullable=False),
    sa.Column('employer_id', sa.String(), nullable=True),
    sa.Column('salary', sa.Float(), nullable=False),
    sa.Column('savings', sa.Float(), nullable=False),
    sa.Column('debt', sa.Float(), nullable=False),
    sa.Column('health_score', sa.Float(), nullable=False),
    sa.Column('stress', sa.Float(), nullable=False),
    sa.Column('alive', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('citizen_id')
    )
    op.create_table('events',
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('simulation_id', sa.String(), nullable=False),
    sa.Column('simulation_tick', sa.Integer(), nullable=False),
    sa.Column('simulation_time', sa.String(), nullable=False),
    sa.Column('source_entity', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('city_id', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_simulation_id'), 'events', ['simulation_id'], unique=False)
    op.create_index(op.f('ix_events_source_entity'), 'events', ['source_entity'], unique=False)
    op.create_table('government',
    sa.Column('simulation_id', sa.String(), nullable=False),
    sa.Column('tax_rate', sa.Float(), nullable=False),
    sa.Column('interest_rate', sa.Float(), nullable=False),
    sa.Column('food_subsidy', sa.Float(), nullable=False),
    sa.Column('healthcare_spending', sa.Float(), nullable=False),
    sa.Column('education_spending', sa.Float(), nullable=False),
    sa.Column('infrastructure_spending', sa.Float(), nullable=False),
    sa.Column('business_regulation', sa.Float(), nullable=False),
    sa.Column('environmental_regulation', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('simulation_id')
    )
    op.create_table('households',
    sa.Column('household_id', sa.String(), nullable=False),
    sa.Column('member_ids', sa.JSON(), nullable=False),
    sa.Column('income', sa.Float(), nullable=False),
    sa.Column('expenses', sa.Float(), nullable=False),
    sa.Column('savings', sa.Float(), nullable=False),
    sa.Column('debt', sa.Float(), nullable=False),
    sa.Column('financial_stress', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('household_id')
    )
    op.create_table('infrastructure',
    sa.Column('building_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('building_id')
    )
    op.create_index(op.f('ix_infrastructure_city_id'), 'infrastructure', ['city_id'], unique=False)
    op.create_index(op.f('ix_infrastructure_kind'), 'infrastructure', ['kind'], unique=False)
    op.create_table('relationships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('simulation_id', sa.String(), nullable=False),
    sa.Column('citizen_id', sa.String(), nullable=False),
    sa.Column('other_id', sa.String(), nullable=False),
    sa.Column('relationship_type', sa.String(), nullable=False),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.Column('trust', sa.Float(), nullable=False),
    sa.Column('frequency', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relationships_citizen_id'), 'relationships', ['citizen_id'], unique=False)
    op.create_index(op.f('ix_relationships_other_id'), 'relationships', ['other_id'], unique=False)
    op.create_index(op.f('ix_relationships_simulation_id'), 'relationships', ['simulation_id'], unique=False)
    op.create_table('simulation_state',
    sa.Column('simulation_id', sa.String(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('tick', sa.Integer(), nullable=False),
    sa.Column('food_price_index', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('simulation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('simulation_state')
    op.drop_index(op.f('ix_relationships_simulation_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_other_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_citizen_id'), table_name='relationships')
    op.drop_table('relationships')
    op.drop_index(op.f('ix_infrastructure_kind'), table_name='infrastructure')
    op.drop_index(op.f('ix_infrastructure_city_id'), table_name='infrastructure')
    op.drop_table('infrastructure')
    op.drop_table('households')
    op.drop_table('government')
    op.drop_index(op.f('ix_events_source_entity'), table_name='events')
    op.drop_index(op.f('ix_events_simulation_id'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_table('events')
    op.drop_table('citizens')
    op.drop_table('businesses')
    op.drop_table('agents')
    # ### end Alembic commands ###
